fix: adds runtime dependencies to authzed
+ Adds missing dependencies. Without runtime dependencies, authzed will not run properly:

```
 require 'authzed'
LoadError: cannot load such file -- google/protobuf
from /Users/somedev/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Caused by LoadError: cannot load such file -- authzed
from /Users/somedev/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
```